// Bundles the website's realistic heart (js/atlas-lab-view.js and its engine
// modules) with the website's three.js into vendor/atlas3d.js (CommonJS,
// minified), using the web app's own vite. Afterwards the bundle's browser
// globals are bound to vendor/atlas-shim.js. The heart model itself is not
// bundled (2.3 MB): the mini program downloads the website's file, whose
// hashed name is read from the web app's dist/ here.
// Run from this folder: node tools/build-vendor.mjs [path/to/apps/cardiac_cycle]
import { createRequire } from "node:module";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const web = resolve(process.argv[2] ?? "../../My_webpage/cycling-metabolism_simulator/apps/cardiac_cycle");
const require = createRequire(web + "/package.json");
const { build } = await import(pathToFileURL(require.resolve("vite")).href);
const three = web + "/node_modules/three";

const glb = (await readdir(web + "/dist/assets")).find((f) => /^heart-atlas-cc07-.*\.glb$/.test(f));
if (!glb) throw new Error("Build the web app first: no dist/assets/heart-atlas-cc07-*.glb");
const SITE = "https://www.kuaiyu.site/cardiac_cycle/";
await writeFile(
  "tools/atlas-asset-stub.js",
  `// Generated by tools/build-vendor.mjs: the website's deployed atlas heart.\nexport const ATLAS_GLB_URL = ${JSON.stringify(SITE + "assets/" + glb)};\nexport const prefetchAtlas = () => {};\nexport const takeAtlasPrefetch = () => null;\n`,
);

await build({
  configFile: false,
  logLevel: "warn",
  resolve: {
    alias: [
      { find: /^three\/addons\/(.*)$/, replacement: three + "/examples/jsm/$1" },
      { find: /^three$/, replacement: three + "/build/three.module.js" },
      { find: /^\.\/atlas-asset\.js$/, replacement: resolve("tools/atlas-asset-stub.js") },
      { find: /^@web\/(.*)$/, replacement: web + "/$1" },
    ],
  },
  build: {
    outDir: resolve("vendor"),
    emptyOutDir: false,
    target: "es2020",
    minify: true,
    lib: { entry: resolve("tools/atlas-entry.js"), formats: ["cjs"], fileName: () => "atlas3d.js" },
  },
});

// Browser globals the bundle uses without a typeof guard (checked 2026-10-09
// against three r180 + the atlas engine), bound to vendor/atlas-shim.js.
const GLOBALS = ["document", "window", "self", "navigator", "performance", "ResizeObserver", "MessageChannel", "AbortController", "TextDecoder", "devicePixelRatio"];
let code = await readFile("vendor/atlas3d.js", "utf8");
for (const name of ["devicePixelRatio", "performance", "document"]) code = code.replaceAll(`globalThis.${name}`, name);
code = `var {${GLOBALS.join(",")}}=require("./atlas-shim.js");\n` + code;
await writeFile("vendor/atlas3d.js", code);
await writeFile("vendor/atlas-asset.js", `// Generated by tools/build-vendor.mjs.\nmodule.exports = { GLB_URL: ${JSON.stringify(SITE + "assets/" + glb)}, CONTENT_URL: ${JSON.stringify(SITE + "content/")} };\n`);
console.log(`vendor/atlas3d.js: ${(code.length / 1024).toFixed(0)} KB; model ${glb}`);
